spring:
  profiles:
    active: test
  group:
    prod: real-slack
---
spring:
  config:
    activate:
      on-profile: test
slack:
  url: test
---
spring:
  config:
    activate:
      on-profile: prod
